### ISSUE TITLE
Can  you please give any references or explain how do you construct the table?

### ISSUE THREAD

**Issue by chamathjayasekara99** [RamadanIbrahem98/threeRocksGame#1]

**Comment by RamadanIbrahem98** [comment]
I had a PDF document explaining the 2-rock game, but when I tried to search for it now, I could not find it.

I basically used the same approach made in that document to solve the 3-rock one.

But could you be more specific? what exactly is not clear? How did I draw the 2D map with colors, or something else?

Doing it from the bottom up, and now is **your move**

| Left Pile | Right Pile |
|:---------:|:----------:|
|     0     |      4     |

now whatever move you make, would result in **computer winning**. so the max movement you can make is (0, 3) which will leave one stone on the right pile, and the computer will do the (0, 1) move and win the game

if you follow the same approach, you will mark the bad **losing** states. for example (0, 4), (1, 3), (2, 2), (3, 1), (4, 0)

Now if it is your move and the board is in the following state 

| Left Pile | Right Pile |
|:---------:|:----------:|
|     0     |      5     |

Then you want to leave the computer with a **losing** state. so you do a (0, 1) move and leave the computer with a (0, 4) pile which is a losing state. now the computer can't do anything but do (for example) a (0, 2) move which will leave the pile as (0, 2), and now it's your move. you can see now how easily you can win the game by playing a (0, 2)


**Please read the previous steps carefully and do it by hand to get a clear understanding of what is happening**

**Comment by chamathjayasekara99** [comment]
I wanted to know how you drew the table, I couldn't see the pattern.

**Comment by chamathjayasekara99** [comment]
Can you please share the 2rock game document.

**Comment by RamadanIbrahem98** [comment]
You can find the solution here in [this PDF](https://nikku1234.github.io/Certification/Data%20Structures%20and%20Algorithms/Learning%20Algorithms%20Through%20Programming%20and%20Puzzle%20Solving%20(%20PDFDrive.com%20).pdf), page number 9 and illustration in page number 10.

**Comment by chamathjayasekara99** [comment]
Thanks for the pdf but thee was no illustration about two rocks game.

**Comment by RamadanIbrahem98** [comment]
Unfortunately, I cannot provide any further help. As I said the PDF document explains the 2-rock game, and I tried to explain the 3-rock game. Do not overthink this. Bring paper and a pencil and try solving it by hand. It's the only way to understand it.

So I will close this issue for now.

**Comment by chamathjayasekara99** [comment]
okay thanks for the help.
